---
title: "yeild_correlation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
library(gplots)
library(lme4)
library(lmerTest)
```
###read in files
```{r warning=FALSE}
as.data.frame(read_delim("sequenced_RP_samples.txt",delim="\t",quote=""))->yield
as.data.frame(read_delim("ko_profile.txt",delim="\t",quote=""))->kotab
rownames(kotab)<-kotab[,1]
kotab<-kotab[,-1]
names(kotab)[3]<-"YL.RS.Si051"
as.data.frame(apply(kotab,2,function(x) x/sum(x)))->kotab
kotab[,yeild[,1]]->retain_tab
```
###calculate coorelation between yeild and ko abundance
```{r include=FALSE,warnig=FALSE}
as.data.frame(matrix(0,nrow=nrow(retain_tab),ncol=3))->corr.tab
names(corr.tab)<-c("corrlation coefficient","pvalue","p.adj")
for (i in 1:nrow(retain_tab)){
  data.frame(abd=as.numeric(retain_tab[i,])*10000,yield=yield[,3],cluster=yield[,4])->new.tab
  lmer(yield~abd+(1|cluster),new.tab)->glm0
  summary(glm0)->summa.glm
  if(nrow(summa.glm$coefficients)==2){
  summa.glm$coefficients[2,1]->corr.tab[i,1]
  summa.glm$coefficients[2,5]->corr.tab[i,2]
  }
}
corr.tab[,3]<-p.adjust(corr.tab[,2],method="BH")
rownames(retain_tab)[which(corr.tab[,3]<0.05 & corr.tab[,1]>0)]->positive.cor.kos
rownames(retain_tab)[which(corr.tab[,3]<0.05 & corr.tab[,1]<0)]->negative.cor.kos
```


###plot
```{r}
mycol<-brewer.pal(8,"Set3")
yield_type<-data.frame(yield=yield[,2])
yield_col<-list(yield = c(I = mycol[1], II=mycol[2],III=mycol[3],IV=mycol[4],V=mycol[5],VI=mycol[6]),corr=c(P=mycol[7],N=mycol[8]))
rownames(yield_type)<-yield[,1]
pon<-data.frame(corr=c(rep("P",length(positive.cor.kos)),rep("N",length(negative.cor.kos))))
rownames(pon)<-c(positive.cor.kos,negative.cor.kos)
retain_tab[c(positive.cor.kos,negative.cor.kos),]->ko_corr.tab
pheatmap(as.matrix(ko_corr.tab),color=redblue(20),cluster_cols = FALSE,cluster_rows = FALSE,scale="row",show_colnames = FALSE,annotation_col = yield_type,annotation_row = pon,annotation_colors = yeild_col[c(1,2)],annotation_legend=FALSE,annotation_names_col = FALSE,annotation_names_row = FALSE,gaps_row = length(positive.cor.kos),fontsize_row = 4,border_color = NA)
```


