---
title: "nitrogen_fixation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(ggsci)
```
###read in files
```{r}
setwd("")
setwd("")
as.data.frame(read_delim("nitrogen_genes_profile_percent.txt",delim="\t",quote=""))->gene.pro
rownames(gene.pro)<-gene.pro[,1]
gene.pro[,-1]->gene.pro
as.data.frame(read_delim("nitrogen_fixation.genes.taxonomy",delim="\t",quote="",col_names=FALSE))->gene.taxonomy
rownames(gene.taxonomy)<-gene.taxonomy[,1]
gene.taxonomy<-gene.taxonomy[,-1]
gene.pro[,grep("RP",names(gene.pro))]->rp.pro
gene.pro[,grep("RS",names(gene.pro))]->rs.pro
apply(rp.pro,1,mean)->rp.pro$mean
apply(rs.pro,1,mean)->rs.pro$mean
```
###add taxonomy
```{r}
sapply(gene.taxonomy[,4],function(x) unlist(strsplit(x,"|",fixed=TRUE))[4])->gene.taxonomy$phylum
sapply(gene.taxonomy[,4],function(x) unlist(strsplit(x,"|",fixed=TRUE))[5])->gene.taxonomy$class
rp.pro$phylum<-gene.taxonomy[rownames(rp.pro),ncol(gene.taxonomy)-1]
rp.pro$class<-gene.taxonomy[rownames(rp.pro),ncol(gene.taxonomy)]
rs.pro$phylum<-gene.taxonomy[rownames(rs.pro),ncol(gene.taxonomy)-1]
rs.pro$class<-gene.taxonomy[rownames(rs.pro),ncol(gene.taxonomy)]
rp.pro[which(is.na(rp.pro),arr.ind = TRUE)]<-"Unclassified"
rs.pro[which(is.na(rs.pro),arr.ind = TRUE)]<-"Unclassified"
aggregate(rs.pro[,ncol(rs.pro)-2],by=list(rs.pro$phylum,rs.pro$class),sum)->data4plot
data4plot[,3]/sum(data4plot[,3])->data4plot[,3]
data4plot[order(data4plot[,3],decreasing=TRUE),]->data4plot
```
###plot
```{r}
paste(data4plot[,2],"(",round(data4plot[,3]*100,2),"%",")",sep="")->data4plot$label
data4plot[grep("Unclassified",data4plot[,4]),4]<-"Unclassified"
#mycols<-c("#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462","#b3de69","#fccde5","#d9d9d9")
mycols<-c("#80b1d3","#eee685","#b2df8a","#33a02c","#fb9a99","#fb8072","#fdbf6f","#ff7f00","#cab2d6")
#ggplot(data4plot,aes(Group.1,x,fill=label))+geom_bar(stat="identity",width=0.9)+coord_polar()+theme(panel.background = element_blank(),axis.ticks = element_blank(),axis.text.y = element_blank(),legend.title = element_blank(),legend.position = "top")+labs(x="",y="")+scale_fill_brewer(palette = "Set3")
ggplot(data4plot,aes(Group.1,x,fill=label))+geom_bar(stat="identity",width=0.9)+coord_polar()+theme(panel.background = element_blank(),axis.ticks = element_blank(),axis.text.y = element_blank(),legend.title = element_blank(),legend.position = "top")+labs(x="",y="")+scale_fill_manual(values = mycols)
```




