---
title: "sequencing_depth_estimation"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(grid)
```
```{r,warning=FALSE}
setwd("")
as.data.frame(read_delim("merge.count_rename.txt",delim="\t",col_names=FALSE))->count.tab
count.tab[,2]<-count.tab[,2]/1000/1000
as.data.frame(read_delim("abundance.final.txt",delim="\t",col_names=FALSE))->abd.tab
#abd.tab[,1]<-factor(abd.tab[,1],levels = unique(abd.tab[,1]))
count.tab[which(count.tab[,1]=="1/4 Lane"),1]<-1
count.tab[which(count.tab[,1]=="2/4 Lane"),1]<-2
count.tab[which(count.tab[,1]=="3/4 Lane"),1]<-3
count.tab[which(count.tab[,1]=="1 Lane"),1]<-4
count.tab[which(count.tab[,1]=="2 Lanes"),1]<-5
count.tab[which(count.tab[,1]=="3 Lanes"),1]<-6
count.tab[which(count.tab[,1]=="4 Lanes"),1]<-7
count.tab[which(count.tab[,1]=="5 Lanes"),1]<-8
count.tab[which(count.tab[,1]=="6 Lanes"),1]<-9
count.tab[which(count.tab[,1]=="7 Lanes"),1]<-10
count.tab[which(count.tab[,3]=="yl_rs2"),3]<-"yl_rs"
count.tab[which(count.tab[,3]=="zjk_rs2"),3]<-"zjk_rs"
count.tab[,1]<-factor(count.tab[,1],levels = unique(count.tab[,1]))
abd.tab[,2]<-factor(abd.tab[,2],levels = 1:10)
```
```{r}
mycols<-c("#ef8a62","#fddbc7","#6baed6","#9ecae1")
ggplot(count.tab,aes(X1,X2,group=X3,color=X3))+geom_smooth(alpha=0.2,size=2.5)+theme(panel.background = element_blank(),axis.line.y = element_line(colour = "black"),legend.key=element_blank(),axis.text.x = element_blank(),axis.ticks.x = element_blank())+xlab("")+ylab("No. of genes mapped(Mb)")+scale_color_manual(values=mycols)+scale_x_discrete(labels=c("1" = "1/4 Lane", "2" = "2/4 Lane","3" = "3/4 Lane","4"="1 Lane","5"="2 Lanes","6"="3 Lanes","7"="4 Lanes","8"="5 Lanes","9"="6 Lanes","10"="7 Lanes"))->p1
ggplot(abd.tab,aes(X2,X3,group=X4,color=X4))+geom_smooth(alpha=0.2,size=2.5)+theme(panel.background = element_blank(),axis.line= element_line(colour = "black"),legend.key=element_blank())+xlab("")+ylab("Cumulative relative abundance of detected genes")+scale_color_manual(values=mycols)+scale_x_discrete(labels=c("1" = "1/4 Lane", "2" = "2/4 Lane","3" = "3/4 Lane","4"="1 Lane","5"="2 Lanes","6"="3 Lanes","7"="4 Lanes","8"="5 Lanes","9"="6 Lanes","10"="7 Lanes"))->p2
grid.draw(rbind(ggplotGrob(p1),ggplotGrob(p2),size="last"))
```



