---
title: "secretome"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(RColorBrewer)
```
###read in files
```{r warning=FALSE}
setwd("")
as.data.frame(read_delim("filter.tax",delim="\t",quote="",col_names=FALSE))->taxonomy
rownames(taxonomy)<-taxonomy[,1]
as.data.frame(read_delim("filter_annotation_best_hit.txt",delim="\t",quote="",col_names=FALSE))->cazymes
rownames(cazymes)<-cazymes[,1]
cazymes<-cazymes[,-1]
as.data.frame(read_delim("paired-samples.txt",delim="\t",quote="",col_names=FALSE))->paired_samples
as.data.frame(read_delim("gene.profile.percent.txt",delim="\t",quote=""))->gene.per.profile
rownames(gene.per.profile)<-gene.per.profile[,1]
gene.per.profile<-gene.per.profile[,-1]
names(gene.per.profile)[3]<-"YL.RS.Si051"
gene.per.profile[,names(gene.per.profile) %in% c(paired_samples[,1],paired_samples[,2])]->paired.gene.profile
paired.gene.profile[,order(names(paired.gene.profile))]->paired.gene.profile
#as.data.frame(apply(paired.gene.profile,2,function(x) x/sum(x)))->paired.gene.profile
```
###add taxonomy and functions
```{r warning=FALSE}
paired.gene.profile$functions<-"Unclassified"
paired.gene.profile[,ncol(paired.gene.profile)]<-cazymes[rownames(paired.gene.profile),2]
paired.gene.profile$taxonomy<-"Unclassified"
sapply(taxonomy[,5],function(x) unlist(strsplit(x,"|",fixed=TRUE))[4])->taxonomy$phylum
taxonomy$phylum[which(is.na(taxonomy$phylum))]<-"Unclassified"
paired.gene.profile$taxonomy<-taxonomy[rownames(paired.gene.profile),ncol(taxonomy)]
paired.gene.profile$taxonomy[which(is.na(paired.gene.profile$taxonomy))]<-"Unclassified"
aggregate(paired.gene.profile[,-c(ncol(paired.gene.profile)-1,ncol(paired.gene.profile))],by=list(paired.gene.profile$functions),sum)->target.pro
aggregate(paired.gene.profile[,-c(ncol(paired.gene.profile)-1,ncol(paired.gene.profile))],by=list(paired.gene.profile$functions,paired.gene.profile$taxonomy),sum)->target.taxonomy.pro
```
###wilcoxon test
```{r}
target.compare<-as.data.frame(matrix(0,nrow=nrow(target.pro),ncol=3))
target.compare[,1]<-target.pro[,1]
for (i in 1:nrow(target.pro)){
  wilcox.test(as.numeric(target.pro[i,grep("RP",colnames(target.pro))]),as.numeric(target.pro[i,grep("RS",colnames(target.pro))]),paired = TRUE,alternative = "greater")$p.value->target.compare[i,2]
}
p.adjust(target.compare$V2,method="BH")->target.compare[,3]
```
###plot
```{r warning=FALSE}
apply(target.taxonomy.pro[,-c(1,2)],2,function(x) x/sum(x))->target.taxonomy.pro[,-c(1,2)]
apply(target.taxonomy.pro[,grep("RP",names(target.taxonomy.pro))],1,mean)->target.taxonomy.pro$mean
for (i in 1:length(unique(target.pro[,1]))){
  target.taxonomy.pro[which(target.taxonomy.pro[,1]==unique(target.pro[,1])[i]),ncol(target.taxonomy.pro)]->filtered
  target.taxonomy.pro$mean[which(target.taxonomy.pro[,1]==unique(target.pro[,1])[i])]<-filtered/sum(filtered)
}
target.taxonomy.pro[,c(1,2,ncol(target.taxonomy.pro))]->table2
table2[which(table2[,3]<0.01),2]<-"Others"
aggregate(table2[,3],by=list(table2[,1],table2[,2]),sum)->table2
reshape2::melt(table2)->data4plot
names(data4plot)[c(1,2)]<-c("Target","Phylum")
#mycols=brewer.pal(9,"Set2")
mycols=c("#80B1D3","#CCEBC5","#FB8072","#FFFFB3","#FDB462","#8DD3C7","#FFED6F","#BC80BD","#D9D9D9","#B3DE69")
ggplot(data4plot,aes(Target,value,fill=Phylum))+geom_bar(stat="identity",width=300)+coord_polar(theta = "y")+theme(axis.ticks = element_blank(),axis.text.y = element_blank(),axis.text.x = element_blank(),panel.border=element_blank(),panel.grid=element_blank(),panel.background = element_blank())+labs(x = "", y = "", title = "")+scale_fill_manual(values = mycols)->p1
p1+facet_wrap(~Target,ncol=3)
```


