---
title: "methods_comparison"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library("ggplot2")
setwd("D:/EÅÌ/millet_meta/methods_comparison/")
source("D:/EÅÌ/millet_meta/Rscripts/multiple.R")
```
```{r}
as.data.frame(read.delim2("anno.profile",sep="\t",quote="",stringsAsFactors=FALSE))->pro.table
rownames(pro.table)<-pro.table[,1]
pro.table<-pro.table[,-1]
as.data.frame(read.delim2("anno.profile.nt",sep="\t",quote="",stringsAsFactors=FALSE))->nt.table
rownames(nt.table)<-nt.table[,1]
nt.table<-nt.table[,-1]
intersect(rownames(pro.table),rownames(nt.table))->over.kos
pro.table[over.kos,]->pro.table
nt.table[over.kos,]->nt.table
pro.abd<-c(pro.table[,1],pro.table[,2],pro.table[,3])
nt.abd<-c(nt.table[,1],nt.table[,2],nt.table[,3])
cor(as.numeric(pro.abd),as.numeric(nt.abd))->corr.pro.nt ##correlation
data.frame(pro=pro.abd,nt=nt.abd,stringsAsFactors=FALSE)->data4plot
as.numeric(data4plot[,1])->data4plot[,1]
as.numeric(data4plot[,2])->data4plot[,2]
data4plot<-data4plot*100
ggplot(data4plot,aes(x=pro,y=nt))+geom_point(alpha=.65,color="#7570b3")+xlab("Relative abundance of KOs profile generated from the AA method (%)")+ylab("Relative abundance of KOs profile generated from the NT method (%)")+geom_abline(slope=1,intercept = 0,color="#ccebc5",size=1,alpha=1)+geom_smooth(method="lm",color="#fbb4ae",alpha=0.7)+xlim(0,0.4)+ylim(0,0.4)+theme_bw()
```

```{r}
comparison_methods<-function(pro.t,nt.t){
  rownames(pro.t)<-pro.t[,1]
  pro.t<-pro.t[,-1]
  rownames(nt.t)<-nt.t[,1]
  nt.t<-nt.t[,-1]
  intersect(rownames(pro.t),rownames(nt.t))->over.names
  pro.t[over.names,]->pro.t
  nt.t[over.names,]->nt.t
  pro.abd<-c(pro.t[,1],pro.t[,2],pro.t[,3])
  nt.abd<-c(nt.t[,1],nt.t[,2],nt.t[,3])
  pro.abd[is.na(pro.abd)]<-0
  nt.abd[is.na(nt.abd)]<-0
  cor(as.numeric(pro.abd),as.numeric(nt.abd))->corr.pro.nt##correlation
  print(corr.pro.nt)
  data.frame(pro=pro.abd,nt=nt.abd,stringsAsFactors=FALSE)->data4plot
  as.numeric(data4plot[,1])->data4plot[,1]
  as.numeric(data4plot[,2])->data4plot[,2]
  #data4plot<-data4plot*100
  ggplot(data4plot,aes(x=pro,y=nt))+geom_point(alpha=.3)+xlab("Taxonomic compositions generated from the AA method(%)")+ylab("Taxonomic compositions generated from the NT method(%)")+geom_abline(slope=1,intercept = 0,color="red",size=1)+geom_smooth(method="lm")+xlim(0,0.3)+ylim(0,0.3)->p
  return(p)
}
```
```{r,warning=FALSE}
as.data.frame(read.delim2("nt_species/indian.nr-tax.profile.phylum",sep="\t",quote="",stringsAsFactors=FALSE))->nt.t
as.data.frame(read.delim2("pro_species/indian.nr-tax.profile.phylum",sep="\t",quote="",stringsAsFactors=FALSE))->pro.t
comparison_methods(pro.t,nt.t)->p1
as.data.frame(read.delim2("nt_species/indian.nr-tax.profile.class",sep="\t",quote="",stringsAsFactors=FALSE))->nt.t
as.data.frame(read.delim2("pro_species/indian.nr-tax.profile.class",sep="\t",quote="",stringsAsFactors=FALSE))->pro.t
comparison_methods(pro.t,nt.t)->p2
as.data.frame(read.delim2("nt_species/indian.nr-tax.profile.order",sep="\t",quote="",stringsAsFactors=FALSE))->nt.t
as.data.frame(read.delim2("pro_species/indian.nr-tax.profile.order",sep="\t",quote="",stringsAsFactors=FALSE))->pro.t
comparison_methods(pro.t,nt.t)->p3
as.data.frame(read.delim2("nt_species/indian.nr-tax.profile.family",sep="\t",quote="",stringsAsFactors=FALSE))->nt.t
as.data.frame(read.delim2("pro_species/indian.nr-tax.profile.family",sep="\t",quote="",stringsAsFactors=FALSE))->pro.t
comparison_methods(pro.t,nt.t)->p4
as.data.frame(read.delim2("nt_species/indian.nr-tax.profile.genus",sep="\t",quote="",stringsAsFactors=FALSE))->nt.t
as.data.frame(read.delim2("pro_species/indian.nr-tax.profile.genus",sep="\t",quote="",stringsAsFactors=FALSE))->pro.t
comparison_methods(pro.t,nt.t)->p5
as.data.frame(read.delim2("nt_species/indian.nr-tax.profile.species",sep="\t",quote="",stringsAsFactors=FALSE))->nt.t
as.data.frame(read.delim2("pro_species/indian.nr-tax.profile.species",sep="\t",quote="",stringsAsFactors=FALSE))->pro.t
comparison_methods(pro.t,nt.t)->p6
multiplot(p1,p2,p3,p4,p5,p6,cols=2)
```


