---
title: "diff_pathway"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggsci)
library(RColorBrewer)
library(readr)
```
###read in files
```{r,warning=FALSE}
setwd("")
as.data.frame(read_delim("pathway_KO.ipath81.wilcox.reporterscore.list",delim="\t",quote=""))->table
as.data.frame(read_delim("map_info",delim="\t",quote="",col_names=FALSE))->mapinfo
gsub("KEGG PATHWAY: | - Reference pathway","",mapinfo[,2])->mapinfo[,2]
rownames(mapinfo)<-mapinfo[,1]
```
###filter results by Z-score
```{r,warning=FALSE}
table[which(abs(table[,6])>1.64 & abs(table[,7])>1.7),c(1,7)]->sig_map
rownames(sig_map)<-sig_map[,1]
sig_map$pathway<-mapinfo[rownames(sig_map),2]
names(sig_map)[2]<-"Zscore"
sig_map[order(sig_map$Zscore),]->sig_map
factor(sig_map[,3],levels=sig_map[,3])->sig_map[,3]
sig_map$flag<-"RS_enrich"
sig_map$flag[which(sig_map[,2]>0)]<-"RP_enrich"
#ggplot(sig_map,aes(pathway,Zscore,fill=flag))+geom_bar(stat="identity")+coord_flip()+theme(axis.ticks.y  = element_blank(),panel.background = element_blank(),axis.text.y = element_text(size=6))+ylab("Reporter Score")+xlab("")+scale_fill_manual(values=c("#C6DBEF","#FDD0A2" ))
ggplot(sig_map,aes(pathway,Zscore,fill=flag))+geom_bar(stat="identity")+coord_flip()+theme(axis.ticks.y  = element_blank(),panel.background = element_blank(),axis.text.y = element_text(size=7))+ylab("Reporter Score")+xlab("")+scale_fill_manual(values=c("#6AA2C7","#E9B15E" ))
```


